// `agent skills install` (docs/skills-design.md §5): copies every skill
// referenced by bindings.yaml for a harness into that harness's discovery
// path (gstack-style host-adapter layer, docs/integrations.md §3 "Adopt
// as design, not code: the hosts/ adapter layer"). generic writes an
// index instead of copying, and never edits AGENTS.md. Idempotent by
// default (already-installed skills are skipped and reported); --force
// overwrites. A skill whose directory cannot be resolved is reported as a
// per-item warning, never a crash — packs may legitimately be absent
// while Wave B/C are still in progress.
import * as fs from "node:fs";
import * as path from "node:path";
import type { BindingsPolicy, Harness } from "./bindings";
import { readBindingsWithFallback, resolveSkillMdPath, parseSkillFrontmatter, skillsForHarness } from "./bindings";
import { ensureDir, writeFileAtomic } from "./fsutil";

const DEFAULT_INSTALL_PATH: Record<"claude-code" | "cursor", string> = {
  "claude-code": ".claude/skills",
  cursor: ".cursor/skills",
};

export type SkillInstallStatus = "installed" | "overwritten" | "skipped" | "missing";

export interface SkillInstallItem {
  relPath: string;
  name?: string;
  status: SkillInstallStatus;
  destDir?: string;
  detail?: string;
}

export interface InstallSkillsResult {
  harness: Harness;
  source: string; // bindings.yaml path actually used (repo or packaged default)
  installDir?: string; // undefined for generic, which writes indexFile instead
  indexFile?: string;
  items: SkillInstallItem[];
}

function collectReferencedSkills(data: BindingsPolicy, harness: Harness): string[] {
  const set = new Set<string>();
  for (const entry of Object.values(data.roles)) {
    for (const s of entry.startup_skills ?? []) set.add(s);
    for (const s of skillsForHarness(entry, harness)) set.add(s);
  }
  return [...set].sort();
}

function copyDirRecursive(src: string, dest: string): void {
  ensureDir(dest);
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirRecursive(srcPath, destPath);
    } else if (entry.isFile()) {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

function installOneToHarnessDir(repo: string, relPath: string, installDir: string, force: boolean): SkillInstallItem {
  const skillMd = resolveSkillMdPath(repo, relPath);
  if (!skillMd) {
    return {
      relPath,
      status: "missing",
      detail: `skill directory not found for '${relPath}' (checked ${repo} and the packaged skills tree)`,
    };
  }
  const fm = parseSkillFrontmatter(skillMd);
  const srcDir = path.dirname(skillMd);
  const destDir = path.join(installDir, fm.name);
  if (fs.existsSync(destDir)) {
    if (!force) {
      return { relPath, name: fm.name, status: "skipped", destDir, detail: "already installed (use --force to overwrite)" };
    }
    fs.rmSync(destDir, { recursive: true, force: true });
    copyDirRecursive(srcDir, destDir);
    return { relPath, name: fm.name, status: "overwritten", destDir };
  }
  copyDirRecursive(srcDir, destDir);
  return { relPath, name: fm.name, status: "installed", destDir };
}

function writeGenericIndex(repo: string, refs: string[], installDirOverride?: string): { indexFile: string; items: SkillInstallItem[] } {
  const items: SkillInstallItem[] = [];
  const rows: { name: string; description: string; path: string }[] = [];
  for (const relPath of refs) {
    const skillMd = resolveSkillMdPath(repo, relPath);
    if (!skillMd) {
      items.push({
        relPath,
        status: "missing",
        detail: `skill directory not found for '${relPath}' (checked ${repo} and the packaged skills tree)`,
      });
      continue;
    }
    const fm = parseSkillFrontmatter(skillMd);
    // Frontmatter descriptions may be multi-line YAML scalars; collapse to a
    // single line so they cannot break the generated Markdown table.
    const description = (fm.description ?? "").replace(/\s+/g, " ").trim();
    rows.push({ name: fm.name, description, path: relPath });
    items.push({ relPath, name: fm.name, status: "installed" });
  }
  const indexFile = installDirOverride
    ? path.join(repo, installDirOverride, "skills-index.md")
    : path.join(repo, ".agent", "skills-index.md");
  const lines = [
    "# Skills Index",
    "",
    "Generated by `agent skills install --harness generic`. Regenerate by re-running that command — do not hand-edit. This file is separate from AGENTS.md and never edits it.",
    "",
    "| name | description | path |",
    "|---|---|---|",
    ...rows.map((r) => `| ${r.name} | ${r.description.replace(/\|/g, "\\|")} | ${r.path} |`),
    "",
  ];
  writeFileAtomic(indexFile, lines.join("\n"));
  return { indexFile, items };
}

export function installSkills(repo: string, opts: { harness?: Harness; force?: boolean } = {}): InstallSkillsResult {
  const { data, source } = readBindingsWithFallback(repo);
  const harness = opts.harness ?? data.active_harness;
  const force = opts.force ?? false;
  const refs = collectReferencedSkills(data, harness);

  if (harness === "generic") {
    const { indexFile, items } = writeGenericIndex(repo, refs, data.install?.generic);
    return { harness, source, indexFile, items };
  }

  const installDirRel = data.install?.[harness] ?? DEFAULT_INSTALL_PATH[harness];
  const installDir = path.join(repo, installDirRel);
  const items = refs.map((relPath) => installOneToHarnessDir(repo, relPath, installDir, force));
  return { harness, source, installDir, items };
}
